# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_login(object):
    def setupUi(self, MainWindow_login):
        MainWindow_login.setObjectName("MainWindow_login")
        MainWindow_login.resize(677, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow_login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 80, 271, 451))
        self.label.setStyleSheet("border-image: url(:/img/img/bg/login.jpg);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 80, 311, 451))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(560, 100, 91, 41))
        self.frame.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_min = QtWidgets.QPushButton(self.frame)
        self.pushButton_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/icon/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.pushButton_min)
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/img/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon1)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 190, 191, 61))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_nickname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nickname.setGeometry(QtCore.QRect(410, 270, 211, 41))
        self.lineEdit_nickname.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgb(0,0,0);")
        self.lineEdit_nickname.setText("")
        self.lineEdit_nickname.setMaxLength(9)
        self.lineEdit_nickname.setObjectName("lineEdit_nickname")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 330, 241, 61))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(400, 410, 231, 51))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_2.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.lineEdit_nickname.raise_()
        self.label_4.raise_()
        self.pushButton_login.raise_()
        MainWindow_login.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_login)
        self.pushButton_close.clicked.connect(MainWindow_login.close)
        self.pushButton_min.clicked.connect(MainWindow_login.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_login)

    def retranslateUi(self, MainWindow_login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_login.setWindowTitle(_translate("MainWindow_login", "MainWindow"))
        self.label_3.setText(_translate("MainWindow_login", "欢迎登录聊天室"))
        self.lineEdit_nickname.setPlaceholderText(_translate("MainWindow_login", "请输入昵称"))
        self.label_4.setText(_translate("MainWindow_login", "昵称请您控制在1-9位，包含字母、数字、和半角的_，区分大小写"))
        self.pushButton_login.setText(_translate("MainWindow_login", "登录"))
import res_rc
